// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderpb/order.proto

package orderpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	CustomerID           string              `protobuf:"bytes,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Items                []*ItemWithQuantity `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *CreateOrderRequest) GetItems() []*ItemWithQuantity {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{1}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *GetOrderRequest) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

type Order struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Items                []*Item  `protobuf:"bytes,4,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Order) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	PriceID              string   `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{3}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetPriceID() string {
	if m != nil {
		return m.PriceID
	}
	return ""
}

type ItemWithQuantity struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemWithQuantity) Reset()         { *m = ItemWithQuantity{} }
func (m *ItemWithQuantity) String() string { return proto.CompactTextString(m) }
func (*ItemWithQuantity) ProtoMessage()    {}
func (*ItemWithQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_87a9833f63666870, []int{4}
}

func (m *ItemWithQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemWithQuantity.Unmarshal(m, b)
}
func (m *ItemWithQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemWithQuantity.Marshal(b, m, deterministic)
}
func (m *ItemWithQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemWithQuantity.Merge(m, src)
}
func (m *ItemWithQuantity) XXX_Size() int {
	return xxx_messageInfo_ItemWithQuantity.Size(m)
}
func (m *ItemWithQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemWithQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_ItemWithQuantity proto.InternalMessageInfo

func (m *ItemWithQuantity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ItemWithQuantity) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "orderpb.CreateOrderRequest")
	proto.RegisterType((*GetOrderRequest)(nil), "orderpb.GetOrderRequest")
	proto.RegisterType((*Order)(nil), "orderpb.Order")
	proto.RegisterType((*Item)(nil), "orderpb.Item")
	proto.RegisterType((*ItemWithQuantity)(nil), "orderpb.ItemWithQuantity")
}

func init() {
	proto.RegisterFile("orderpb/order.proto", fileDescriptor_87a9833f63666870)
}

var fileDescriptor_87a9833f63666870 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x69, 0x9a, 0xbe, 0x3c, 0xd3, 0xc7, 0x2a, 0x2b, 0x94, 0x98, 0x82, 0x94, 0x78, 0xe9,
	0xc5, 0x2c, 0xc4, 0x7a, 0xf5, 0xd0, 0x56, 0xa4, 0x08, 0xbe, 0x44, 0x44, 0xf0, 0x64, 0x92, 0x4e,
	0xd3, 0x80, 0xdb, 0x8d, 0xc9, 0xa6, 0xd0, 0x7e, 0x39, 0xbf, 0x9a, 0x64, 0xf3, 0x42, 0x9b, 0x22,
	0x9e, 0x92, 0xff, 0xec, 0xcc, 0xfc, 0xf8, 0xcf, 0x0c, 0x9c, 0xf2, 0x68, 0x8e, 0x51, 0xe8, 0x52,
	0xf9, 0x35, 0xc3, 0x88, 0x0b, 0x4e, 0x5a, 0x79, 0x50, 0xef, 0xfb, 0x9c, 0xfb, 0x9f, 0x48, 0x65,
	0xd8, 0x4d, 0x16, 0x14, 0x59, 0x28, 0x36, 0x59, 0x96, 0x81, 0x40, 0x26, 0x11, 0x3a, 0x02, 0x1f,
	0xd3, 0x6c, 0x1b, 0xbf, 0x12, 0x8c, 0x05, 0x39, 0x07, 0x98, 0x24, 0xb1, 0xe0, 0x0c, 0xa3, 0xd9,
	0x54, 0xab, 0x0d, 0x6a, 0xc3, 0x7f, 0xf6, 0x4e, 0x84, 0x50, 0x68, 0xcc, 0x04, 0xb2, 0x58, 0x53,
	0x06, 0xf5, 0x61, 0xc7, 0x3a, 0x33, 0x73, 0x96, 0x99, 0x46, 0xdf, 0x02, 0xb1, 0x7c, 0x4e, 0x9c,
	0x95, 0x08, 0xc4, 0xc6, 0xce, 0xf2, 0x8c, 0x7b, 0x38, 0xbe, 0x43, 0xb1, 0xc7, 0xd0, 0xa0, 0x25,
	0x75, 0x09, 0x28, 0x64, 0x85, 0xae, 0x54, 0xe9, 0x86, 0x80, 0x86, 0x4c, 0x25, 0x5d, 0x50, 0xca,
	0x6a, 0xe5, 0xef, 0x42, 0xd2, 0x83, 0x66, 0x2c, 0x1c, 0x91, 0xc4, 0x5a, 0x5d, 0xbe, 0xe5, 0x8a,
	0x5c, 0x14, 0x76, 0x54, 0x69, 0xe7, 0x68, 0xcf, 0x4e, 0x61, 0xe1, 0x03, 0xd4, 0xf4, 0xe7, 0x00,
	0x4a, 0x40, 0x7d, 0x70, 0x18, 0xe6, 0x38, 0xf9, 0x4f, 0x74, 0x68, 0x17, 0x13, 0x90, 0xa8, 0x86,
	0x5d, 0xea, 0xd4, 0xf7, 0x53, 0x14, 0x78, 0x38, 0x9b, 0x6a, 0x6a, 0xe6, 0x3b, 0x97, 0xc6, 0x0d,
	0x9c, 0x54, 0xe7, 0x77, 0x40, 0xdb, 0xed, 0xac, 0xec, 0x77, 0xb6, 0xbe, 0x6b, 0xf0, 0x5f, 0x0e,
	0xe6, 0x05, 0xa3, 0x75, 0xe0, 0x21, 0x19, 0x43, 0x67, 0x67, 0xb9, 0xa4, 0x5f, 0xfa, 0x3a, 0x5c,
	0xb9, 0xde, 0x33, 0xb3, 0x33, 0x31, 0x8b, 0x33, 0x31, 0x6f, 0xd3, 0x33, 0x21, 0x23, 0x68, 0x17,
	0x9b, 0x23, 0x5a, 0xd9, 0xa0, 0xb2, 0x4c, 0xbd, 0x5b, 0xbe, 0x64, 0x99, 0xd7, 0xd0, 0x79, 0x0d,
	0xe7, 0x25, 0xb9, 0xf2, 0xfc, 0x1b, 0x6c, 0x3c, 0x7a, 0xb7, 0xfc, 0x40, 0x2c, 0x13, 0xd7, 0xf4,
	0x38, 0xa3, 0x6c, 0xb1, 0xdd, 0x2e, 0xa8, 0x2f, 0x4b, 0x2f, 0xd7, 0x16, 0xf5, 0x38, 0x63, 0x7c,
	0x45, 0x7d, 0x5c, 0xc9, 0x32, 0x9a, 0xf7, 0x74, 0x9b, 0x52, 0x5e, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x25, 0x04, 0xe9, 0xc9, 0x07, 0x03, 0x00, 0x00,
}
